/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_admin_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Whether the stored token is still valid (the UI checks it on load).
         */
        get: operations["me_api_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_admin_sources_get"];
        put?: never;
        /**
         * Add Source
         * @description Paste a link: the server decides the rest. robots.txt first (nothing is fetched from a site that forbids it);
         *     then kind (PDF/DOC/DOCX by content type or extension, else a site), category by rules (no LLM), crawl settings;
         *     the job is queued at once. A second link of a domain that is already a source goes into that source.
         */
        post: operations["add_source_api_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_api_admin_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/api/admin/sources/{source_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job */
        post: operations["start_job_api_admin_sources__source_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_admin_jobs_get"];
        put?: never;
        post?: never;
        /**
         * Clear Jobs
         * @description Removes the finished jobs from the history (queued and running ones stay).
         */
        delete: operations["clear_jobs_api_admin_jobs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_admin_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_admin_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_admin_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Runs a finished job's work again as a new job.
         */
        post: operations["retry_job_api_admin_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Low Rated */
        get: operations["low_rated_api_admin_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/feedback/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Stats */
        get: operations["feedback_stats_api_admin_feedback_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Suggestions
         * @description Every quick question once, with its texts in every language and whether it is shown yet.
         */
        get: operations["admin_suggestions_api_admin_suggestions_get"];
        put?: never;
        /**
         * Pin Suggestion
         * @description A question the admin wants among the quick questions; shown once the next re-check answers it well.
         */
        post: operations["pin_suggestion_api_admin_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/suggestions/{suggestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hide Suggestion */
        delete: operations["hide_suggestion_api_admin_suggestions__suggestion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gaps
         * @description Similar not_found / partial questions grouped (local embeddings, no LLM), biggest groups first.
         */
        get: operations["list_gaps_api_admin_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gaps/{gap_id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recheck Gap
         * @description Asks the group's example again (one model call, only on this click). Answered now → the group leaves the
         *     default list.
         */
        post: operations["recheck_gap_api_admin_gaps__gap_id__recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gaps/{gap_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide Gap */
        post: operations["hide_gap_api_admin_gaps__gap_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gaps/{gap_id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unhide Gap */
        post: operations["unhide_gap_api_admin_gaps__gap_id__unhide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_admin_llm_get"];
        /** Save Settings */
        put: operations["save_settings_api_admin_llm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Models */
        post: operations["provider_models_api_admin_llm_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/llm/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model */
        post: operations["test_model_api_admin_llm_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_admin_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/usage/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pricing */
        get: operations["get_pricing_api_admin_usage_pricing_get"];
        /** Save Pricing */
        put: operations["save_pricing_api_admin_usage_pricing_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_api_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback
         * @description 1-5 stars (or the older up/down vote), reason tags, comment. Stored in Postgres with the question, status,
         *     cited documents and path of the answer.
         */
        post: operations["feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/outdated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Outdated
         * @description The preview didn't find a cited passage on the live page: the site is checked sooner (at most every 6 h).
         */
        post: operations["outdated_api_signals_outdated_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document File
         * @description The PDF for the source viewer, fetched from the city hall site by the URL in our index.
         */
        get: operations["document_file_api_documents__doc_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Preview
         * @description The cited source for the chat's iframe: the page (our sanitized copy) or the PDF (pdf.js), scrolled to the
         *     quoted lines and highlighted; DOCX and unreachable pages as our text view. See spott/api/preview.py.
         */
        get: operations["source_preview_api_preview__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggestions
         * @description Real questions we know we answer well (answered, verified, re-checked against the current index).
         */
        get: operations["suggestions_api_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Visit
         * @description Counts this browser once (its anonymous id) and returns the number of unique visitors, for the header.
         */
        post: operations["visit_api_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminLogin */
        AdminLogin: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** AdminMe */
        AdminMe: {
            /** Login */
            login: string;
        };
        /** AdminSession */
        AdminSession: {
            /** Token */
            token: string;
            /** Login */
            login: string;
            /** Expires At */
            expires_at: string;
        };
        /** AnswerMeta */
        AnswerMeta: {
            /** Model */
            model: string | null;
            /**
             * Path
             * @enum {string}
             */
            path: "fast" | "agent" | "none" | "cache";
            /** Latency Ms */
            latency_ms: number;
            /** Verified */
            verified: boolean;
        };
        /** AnswerSentence */
        AnswerSentence: {
            /** Text */
            text: string;
            /** Cites */
            cites: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Lang */
            lang?: ("ro" | "ru" | "en") | null;
            /**
             * History
             * @default []
             */
            history?: components["schemas"]["ChatTurn"][];
            page_context?: components["schemas"]["PageContext"] | null;
            /**
             * Mode
             * @default auto
             * @enum {string}
             */
            mode?: "auto" | "fast" | "deep";
            /** Session Id */
            session_id?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "partial" | "not_found" | "conflict" | "refused";
            /**
             * Lang
             * @enum {string}
             */
            lang: "ro" | "ru" | "en";
            /** Answer */
            answer: string;
            /** Sentences */
            sentences: components["schemas"]["AnswerSentence"][];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            conflict: components["schemas"]["ConflictInfo"] | null;
            checklist: components["schemas"]["Checklist"] | null;
            /** Nav Links */
            nav_links: components["schemas"]["NavLink"][];
            /** Followups */
            followups: string[];
            /** Trace */
            trace: components["schemas"]["TraceStep"][];
            meta: components["schemas"]["AnswerMeta"];
            /** Focus Citation Id */
            focus_citation_id?: string | null;
            /**
             * Contacts
             * @default []
             */
            contacts?: components["schemas"]["ContactCard"][];
        };
        /**
         * BBox
         * @description PDF points, origin top-left.
         */
        BBox: {
            /** Page */
            page: number;
            /** L */
            l: number;
            /** T */
            t: number;
            /** R */
            r: number;
            /** B */
            b: number;
            /** Page Width */
            page_width: number;
            /** Page Height */
            page_height: number;
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
        };
        /** Checklist */
        Checklist: {
            /** Title */
            title: string;
            /** Steps */
            steps: components["schemas"]["ChecklistStep"][];
            /** Documents Needed */
            documents_needed: string[];
            /** Fee */
            fee: string | null;
            /** Deadline */
            deadline: string | null;
        };
        /** ChecklistStep */
        ChecklistStep: {
            /** Text */
            text: string;
            /** Cites */
            cites: string[];
        };
        /** Citation */
        Citation: {
            /** Id */
            id: string;
            /** Doc Id */
            doc_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Line Ids */
            line_ids: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "page";
            /** Document Title */
            document_title: string;
            /** Doc Type */
            doc_type: string | null;
            /** Act Number */
            act_number: string | null;
            /** Published */
            published: string | null;
            /** Location */
            location: string | null;
            /** Page */
            page: number | null;
            /** Quote */
            quote: string;
            /**
             * Quote Lang
             * @enum {string}
             */
            quote_lang: "ro" | "ru" | "en" | "uk";
            /** Translation */
            translation: string | null;
            /** Url */
            url: string;
            /** Deep Link */
            deep_link: string;
            /** Found On */
            found_on: string | null;
            /** Site */
            site: string | null;
            /** File Url */
            file_url: string | null;
            /** Bboxes */
            bboxes: components["schemas"]["BBox"][];
            /** Preview Url */
            preview_url: string;
            /**
             * Preview Kind
             * @enum {string}
             */
            preview_kind: "page" | "pdf" | "text";
        };
        /** ConflictInfo */
        ConflictInfo: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "outdated" | "contradiction";
            /** Explanation */
            explanation: string;
            /** Citation Ids */
            citation_ids: string[];
            /** Preferred Citation Id */
            preferred_citation_id: string | null;
        };
        /**
         * ContactCard
         * @description Who can help when the documents don't answer: every phone, e-mail and address is in its line_ids.
         */
        ContactCard: {
            /** Name */
            name: string;
            /** Area */
            area: string | null;
            /** Phone */
            phone: string[];
            /** Email */
            email: string[];
            /** Address */
            address: string | null;
            /** Hours */
            hours: string | null;
            /** Url */
            url: string;
            /** Site */
            site: string;
            /** Reason */
            reason: string;
            /** Line Ids */
            line_ids: string[];
            /** Deep Link */
            deep_link: string;
        };
        /** CorpusTotals */
        CorpusTotals: {
            /** Sites Total */
            sites_total: number;
            /** Sites Indexed */
            sites_indexed: number;
            /** Pages */
            pages: number;
            /** Documents Found */
            documents_found: number;
            /** Documents Downloaded */
            documents_downloaded: number;
            /** Chunks */
            chunks: number;
            /** Lines */
            lines: number;
            /** Documents Replaced */
            documents_replaced: number;
            /** Documents Removed */
            documents_removed: number;
        };
        /** Day */
        Day: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** FeedbackDay */
        FeedbackDay: {
            /** Day */
            day: string;
            /** Count */
            count: number;
            /** Average */
            average: number;
        };
        /** FeedbackItem */
        FeedbackItem: {
            /** Answer Id */
            answer_id: string;
            /** Rating */
            rating: number;
            /** Tags */
            tags: ("wrong" | "outdated" | "incomplete" | "wrong_source" | "not_understood" | "helpful")[];
            /** Comment */
            comment: string | null;
            /** Question */
            question: string | null;
            /** Lang */
            lang: ("ro" | "ru" | "en") | null;
            /** Status */
            status: ("answered" | "partial" | "not_found" | "conflict" | "refused") | null;
            /** Answer */
            answer: string | null;
            /** Doc Ids */
            doc_ids: string[];
            /** Path */
            path: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** FeedbackList */
        FeedbackList: {
            /** Items */
            items: components["schemas"]["FeedbackItem"][];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Answer Id */
            answer_id: string;
            /** Rating */
            rating?: number | null;
            /** Vote */
            vote?: ("up" | "down") | null;
            /**
             * Tags
             * @default []
             */
            tags?: ("wrong" | "outdated" | "incomplete" | "wrong_source" | "not_understood" | "helpful")[];
            /** Comment */
            comment?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Ok */
            ok: boolean;
        };
        /** FeedbackStats */
        FeedbackStats: {
            /** Count */
            count: number;
            /** Average */
            average: number | null;
            /** Per Star */
            per_star: {
                [key: string]: number;
            };
            /** Top Tags */
            top_tags: components["schemas"]["TagCount"][];
            /** By Day */
            by_day: components["schemas"]["FeedbackDay"][];
        };
        /** Gap */
        Gap: {
            /** Id */
            id: string;
            /** Example */
            example: string;
            title?: components["schemas"]["GapTitle"] | null;
            /** Questions */
            questions: components["schemas"]["GapQuestion"][];
            /** Count */
            count: number;
            /** Last Asked */
            last_asked: string;
            /** Langs */
            langs: ("ro" | "ru" | "en")[];
            /**
             * Status
             * @enum {string}
             */
            status: "not_found" | "partial";
            /** Missing */
            missing: string[];
            /** Hint Sites */
            hint_sites: components["schemas"]["GapSite"][];
            rechecked: components["schemas"]["GapRecheck"] | null;
            /** Hidden */
            hidden: boolean;
            /**
             * Topic
             * @default other
             * @enum {string}
             */
            topic?: "transport" | "urbanism" | "education" | "health" | "social" | "utilities" | "taxes" | "documents" | "council" | "environment" | "culture" | "other";
            /** Last Answer */
            last_answer?: string | null;
        };
        /** GapList */
        GapList: {
            /** Items */
            items: components["schemas"]["Gap"][];
            totals: components["schemas"]["GapTotals"];
            /**
             * Topics
             * @default []
             */
            topics?: components["schemas"]["GapTopic"][];
        };
        /** GapQuestion */
        GapQuestion: {
            /** Answer Id */
            answer_id: string;
            /** Question */
            question: string;
            /**
             * Lang
             * @enum {string}
             */
            lang: "ro" | "ru" | "en";
            /**
             * Status
             * @enum {string}
             */
            status: "not_found" | "partial";
            /** Ts */
            ts: string;
        };
        /** GapRecheck */
        GapRecheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "partial" | "not_found" | "conflict" | "refused";
            /** Verified */
            verified: boolean;
            /** Answer Id */
            answer_id: string;
            /** Ts */
            ts: string;
        };
        /** GapSite */
        GapSite: {
            /** Site */
            site: string;
            /** Hits */
            hits: number;
        };
        /** GapTitle */
        GapTitle: {
            /** Ro */
            ro: string;
            /** Ru */
            ru: string;
        };
        /** GapTopic */
        GapTopic: {
            /**
             * Topic
             * @enum {string}
             */
            topic: "transport" | "urbanism" | "education" | "health" | "social" | "utilities" | "taxes" | "documents" | "council" | "environment" | "culture" | "other";
            /** Groups */
            groups: number;
        };
        /** GapTotals */
        GapTotals: {
            /** Not Found */
            not_found: number;
            /** Partial */
            partial: number;
            /** Groups */
            groups: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Device */
            device: string;
            /** Models Loaded */
            models_loaded: boolean;
            /** Chunk Count */
            chunk_count: number;
        };
        /** Job */
        Job: {
            /** Id */
            id: number;
            /** Source Id */
            source_id: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "crawl" | "refresh" | "check" | "backlog";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            /** Stage */
            stage: ("crawl" | "download" | "parse" | "index") | null;
            /** Stage Done */
            stage_done: number;
            /** Stage Total */
            stage_total: number;
            /** Percent */
            percent: number;
            /** Eta S */
            eta_s: number | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Log Tail */
            log_tail: string[];
            /** Error */
            error: string | null;
        };
        /** JobCreate */
        JobCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "crawl" | "refresh";
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** KindRow */
        KindRow: {
            /** Kind */
            kind: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** LLMSettingsUpdate */
        LLMSettingsUpdate: {
            /**
             * Providers
             * @default {}
             */
            providers?: {
                [key: string]: components["schemas"]["ProviderUpdate"];
            };
            /**
             * Roles
             * @default {}
             */
            roles?: {
                [key: string]: components["schemas"]["RoleModel"] | null;
            };
        };
        /** LLMSettingsView */
        LLMSettingsView: {
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
            /** Roles */
            roles: {
                [key: string]: components["schemas"]["RoleView"] | null;
            };
        };
        /** ModelCheck */
        ModelCheck: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini" | "custom";
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model: string;
        };
        /** ModelList */
        ModelList: {
            /** Models */
            models: string[];
        };
        /** ModelRow */
        ModelRow: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
            price: components["schemas"]["Price"] | null;
        };
        /** ModelTest */
        ModelTest: {
            /** Ok */
            ok: boolean;
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error?: string | null;
        };
        /** NavLink */
        NavLink: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "page" | "service" | "contact" | "document";
            /** Selector */
            selector?: string | null;
        };
        /** PageContext */
        PageContext: {
            /** Url */
            url?: string | null;
            /** Title */
            title?: string | null;
        };
        /** Price */
        Price: {
            /** Input */
            input: number;
            /** Output */
            output: number;
        };
        /** Pricing */
        Pricing: {
            /**
             * Currency
             * @default USD
             * @enum {string}
             */
            currency?: "USD" | "EUR" | "MDL";
            /** Rates */
            rates?: {
                [key: string]: number;
            };
            /**
             * Prices
             * @default {}
             */
            prices?: {
                [key: string]: components["schemas"]["Price"];
            };
            /** Budget Usd */
            budget_usd?: number | null;
        };
        /** ProviderCheck */
        ProviderCheck: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini" | "custom";
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ProviderView */
        ProviderView: {
            /**
             * Id
             * @enum {string}
             */
            id: "openai" | "anthropic" | "gemini" | "custom";
            /** Label */
            label: string;
            /**
             * Api
             * @enum {string}
             */
            api: "openai" | "anthropic";
            /** Needs Key */
            needs_key: boolean;
            /** Needs Url */
            needs_url: boolean;
            /** Has Key */
            has_key: boolean;
            /** Key Hint */
            key_hint?: string | null;
            /** Key Source */
            key_source?: ("admin" | "env") | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Url */
            default_url?: string | null;
        };
        /** RoleModel */
        RoleModel: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini" | "custom";
            /** Model */
            model: string;
        };
        /** RoleView */
        RoleView: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini" | "custom";
            /** Model */
            model: string;
            /**
             * Source
             * @enum {string}
             */
            source: "admin" | "env";
        };
        /** SourceAdded */
        SourceAdded: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "site" | "document";
            /** Url */
            url: string;
            /** Site Id */
            site_id: string;
            /** Title */
            title: string | null;
            /** Category */
            category: string | null;
            /** Category Source */
            category_source: string | null;
            /** Start Urls */
            start_urls: string[];
            /** Max Depth */
            max_depth: number | null;
            /** Max Pages */
            max_pages: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Robots
             * @enum {string}
             */
            robots: "allowed" | "blocked";
            /**
             * Status
             * @enum {string}
             */
            status: "indexed" | "pending" | "running" | "queued" | "failed" | "blocked" | "disabled";
            /** Pages */
            pages: number;
            /** Documents Found */
            documents_found: number;
            /** Documents Downloaded */
            documents_downloaded: number;
            /** Chunks */
            chunks: number;
            /** Lines */
            lines: number;
            /** Last Crawled */
            last_crawled: string | null;
            progress: components["schemas"]["SourceProgress"] | null;
            /** Last Error */
            last_error: string | null;
            /** Created At */
            created_at: string;
            last_job: components["schemas"]["Job"] | null;
            /**
             * Auto Update
             * @default true
             */
            auto_update?: boolean;
            /** Check Method */
            check_method?: string | null;
            /** Last Checked At */
            last_checked_at?: string | null;
            /** Next Check At */
            next_check_at?: string | null;
            /**
             * Stale Signals
             * @default 0
             */
            stale_signals?: number;
            /**
             * Crawl Left
             * @default 0
             */
            crawl_left?: number;
            /**
             * Documents Pending
             * @default 0
             */
            documents_pending?: number;
            /**
             * Files Pending
             * @default 0
             */
            files_pending?: number;
            /**
             * Pages Pending
             * @default 0
             */
            pages_pending?: number;
            detected: components["schemas"]["SourceDetected"];
            /** Merged Into */
            merged_into: number | null;
        };
        /**
         * SourceCreate
         * @description Only `url` is needed: the server decides the kind, category and crawl settings. The other fields are
         *     accepted for older clients and override what the server would decide.
         */
        SourceCreate: {
            /** Url */
            url: string;
            /** Kind */
            kind?: ("site" | "document") | null;
            /** Category */
            category?: string | null;
            /** Max Depth */
            max_depth?: number | null;
            /** Max Pages */
            max_pages?: number | null;
            /**
             * Start
             * @default true
             */
            start?: boolean;
        };
        /** SourceDetected */
        SourceDetected: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "site" | "document";
            /** Category */
            category: string;
            /** Category Source */
            category_source: string;
            /** Title */
            title: string | null;
            /** Crawl Depth */
            crawl_depth: number | null;
            /** Max Pages */
            max_pages: number | null;
            /** Reason */
            reason: string;
        };
        /** SourceList */
        SourceList: {
            /** Sources */
            sources: components["schemas"]["SourceRow"][];
            totals: components["schemas"]["CorpusTotals"];
        };
        /** SourcePatch */
        SourcePatch: {
            /** Enabled */
            enabled?: boolean | null;
            /** Auto Update */
            auto_update?: boolean | null;
            /** Max Depth */
            max_depth?: number | null;
            /** Max Pages */
            max_pages?: number | null;
            /** Category */
            category?: string | null;
        };
        /** SourceProgress */
        SourceProgress: {
            /** Job Id */
            job_id: number;
            /** Stage */
            stage: ("crawl" | "download" | "parse" | "index") | null;
            /** Percent */
            percent: number;
            /** Eta S */
            eta_s: number | null;
            /** Current */
            current?: string | null;
        };
        /**
         * SourceRow
         * @description One row of the admin's single sources table: everything it shows, from one call.
         */
        SourceRow: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "site" | "document";
            /** Url */
            url: string;
            /** Site Id */
            site_id: string;
            /** Title */
            title: string | null;
            /** Category */
            category: string | null;
            /** Category Source */
            category_source: string | null;
            /** Start Urls */
            start_urls: string[];
            /** Max Depth */
            max_depth: number | null;
            /** Max Pages */
            max_pages: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Robots
             * @enum {string}
             */
            robots: "allowed" | "blocked";
            /**
             * Status
             * @enum {string}
             */
            status: "indexed" | "pending" | "running" | "queued" | "failed" | "blocked" | "disabled";
            /** Pages */
            pages: number;
            /** Documents Found */
            documents_found: number;
            /** Documents Downloaded */
            documents_downloaded: number;
            /** Chunks */
            chunks: number;
            /** Lines */
            lines: number;
            /** Last Crawled */
            last_crawled: string | null;
            progress: components["schemas"]["SourceProgress"] | null;
            /** Last Error */
            last_error: string | null;
            /** Created At */
            created_at: string;
            last_job: components["schemas"]["Job"] | null;
            /**
             * Auto Update
             * @default true
             */
            auto_update?: boolean;
            /** Check Method */
            check_method?: string | null;
            /** Last Checked At */
            last_checked_at?: string | null;
            /** Next Check At */
            next_check_at?: string | null;
            /**
             * Stale Signals
             * @default 0
             */
            stale_signals?: number;
            /**
             * Crawl Left
             * @default 0
             */
            crawl_left?: number;
            /**
             * Documents Pending
             * @default 0
             */
            documents_pending?: number;
            /**
             * Files Pending
             * @default 0
             */
            files_pending?: number;
            /**
             * Pages Pending
             * @default 0
             */
            pages_pending?: number;
        };
        /**
         * StaleSignal
         * @description A cited passage the preview no longer finds on the live page.
         */
        StaleSignal: {
            /** Doc Id */
            doc_id: string;
        };
        /** Suggestion */
        Suggestion: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /**
             * Lang
             * @enum {string}
             */
            lang: "ro" | "ru" | "en";
            /** Answer Id */
            answer_id: string | null;
            /** Asked Count */
            asked_count: number;
            /** Rating Avg */
            rating_avg: number | null;
            /** Pinned */
            pinned: boolean;
            /** Check */
            check?: ("ok" | "pending" | "failed") | null;
            /** Texts */
            texts?: {
                [key: string]: string;
            } | null;
        };
        /** SuggestionCreate */
        SuggestionCreate: {
            /** Question */
            question: string;
            /**
             * Lang
             * @enum {string}
             */
            lang: "ro" | "ru" | "en";
            /**
             * Pinned
             * @default true
             */
            pinned?: boolean;
        };
        /** SuggestionList */
        SuggestionList: {
            /** Items */
            items: components["schemas"]["Suggestion"][];
        };
        /** TagCount */
        TagCount: {
            /**
             * Tag
             * @enum {string}
             */
            tag: "wrong" | "outdated" | "incomplete" | "wrong_source" | "not_understood" | "helpful";
            /** Count */
            count: number;
        };
        /** Totals */
        Totals: {
            /**
             * Calls
             * @default 0
             */
            calls?: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens?: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens?: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd?: number;
            /**
             * Unpriced Calls
             * @default 0
             */
            unpriced_calls?: number;
        };
        /** TraceStep */
        TraceStep: {
            /**
             * Tool
             * @enum {string}
             */
            tool: "search" | "grep" | "toc" | "open" | "verify";
            /** Input */
            input: string;
            /** Summary */
            summary: string;
            /** Ms */
            ms: number;
        };
        /** UsageReport */
        UsageReport: {
            /** Days */
            days: number;
            pricing: components["schemas"]["Pricing"];
            today: components["schemas"]["Totals"];
            month: components["schemas"]["Totals"];
            /** Month Forecast Usd */
            month_forecast_usd: number;
            range: components["schemas"]["Totals"];
            all_time: components["schemas"]["Totals"];
            /** Questions */
            questions: number;
            /** Cost Per Question Usd */
            cost_per_question_usd: number | null;
            /** Daily */
            daily: components["schemas"]["Day"][];
            /** Models */
            models: components["schemas"]["ModelRow"][];
            /** Kinds */
            kinds: components["schemas"]["KindRow"][];
            /** Known Models */
            known_models: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitRequest */
        VisitRequest: {
            /** Visitor Id */
            visitor_id: string;
        };
        /** VisitorCount */
        VisitorCount: {
            /** Visitors */
            visitors: number;
        };
        /** ApiError */
        ApiError: {
            /**
             * Error
             * @enum {string}
             */
            error: "validation_error" | "unauthorized" | "not_found" | "conflict" | "rate_limited" | "unavailable" | "not_implemented" | "internal";
            /** Message */
            message: string;
            /**
             * Retry After S
             * @default null
             */
            retry_after_s?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_admin_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMe"];
                };
            };
        };
    };
    list_sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    add_source_api_admin_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description merged into a source of the same domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdded"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_admin_sources__source_id__delete: {
        parameters: {
            query?: {
                purge?: boolean;
            };
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_api_admin_sources__source_id__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_admin_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_jobs_api_admin_jobs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_job_api_admin_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_admin_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_admin_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_admin_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_rated_api_admin_feedback_get: {
        parameters: {
            query?: {
                max_rating?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_stats_api_admin_feedback_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackStats"];
                };
            };
        };
    };
    admin_suggestions_api_admin_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
        };
    };
    pin_suggestion_api_admin_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_suggestion_api_admin_suggestions__suggestion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gaps_api_admin_gaps_get: {
        parameters: {
            query?: {
                status?: string;
                lang?: string | null;
                days?: number;
                limit?: number;
                hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recheck_gap_api_admin_gaps__gap_id__recheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapRecheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_gap_api_admin_gaps__gap_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unhide_gap_api_admin_gaps__gap_id__unhide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_admin_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingsView"];
                };
            };
        };
    };
    save_settings_api_admin_llm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMSettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_models_api_admin_llm_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCheck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_api_admin_llm_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCheck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelTest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_admin_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pricing_api_admin_usage_pricing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pricing"];
                };
            };
        };
    };
    save_pricing_api_admin_usage_pricing_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Pricing"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pricing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outdated_api_signals_outdated_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaleSignal"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_file_api_documents__doc_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_preview_api_preview__doc_id__get: {
        parameters: {
            query?: {
                line?: string[] | null;
                lang?: string;
                embed?: number;
            };
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_api_suggestions_get: {
        parameters: {
            query?: {
                lang?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visit_api_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
